app/protected/controllers/PostsController.php
<?php

class PostsController extends BaseController
{
	public $pageTitle = 'Форум';
	
	public function init()
	{
		parent::init();
		
		$this->breadcrumbs = array(
			$this->pageTitle => array('index'),
		);
	}
	
	public function accessRules()
    {
        return array_merge(
			array(
				array('allow',
					'actions' => array('index')),
			),
			parent::accessRules()
		);
    }
	
	public function filters()
	{
        return array_merge(
			array(
				'postOnly + delete'
			),
			parent::filters()
		);
	}
	
	public function actionReply($to = null)
	{
		$parent_post = $this->loadModel($to);
		$model = new ForumPosts;

		$this->performAjaxValidation($model);

		if ( isset($_POST['ForumPosts']) )
		{
			$post_data = $_POST['ForumPosts'];
			$post_data['thread_id'] = $parent_post->thread_id;
			$post_data['parent_post_id'] = $parent_post->id;
			if ( $model->create($post_data) )
				$this->redirect(array('/threads/view', 'id' => $parent_post->thread_id ));
		}

		$this->render('reply',array(
			'model' => $model,
			'parent_post' => $parent_post,
		));
	}
	
	public function loadModel($id)
	{
		$model = ForumPosts::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}
	
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'posts-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/views/widgets/event-calendar-month.php
<div id="<?php echo $this->id; ?>" class="<?php echo $this->{'class'}; ?>">
<?php echo $title ? XHtml::tag('div', array('class' => 'title'), $title) : ''; ?>
<table>
<thead>
	<tr>
		<th>ПН</th>
		<th>ВТ</th>
		<th>СР</th>
		<th>ЧТ</th>
		<th>ПТ</th>
		<th class="weekend">СБ</th>
		<th class="weekend">ВС</th>
	</tr>
</thead>
<tbody>
<?php for ($t = $begins_with; $t < $ends_to; ) { ?>
	<tr>
	<?php
		for ($n = 1; $n <= 7; $n++, $t += 60*60*24)
		{
			$d = getdate($t);
			
			$html_classes = array();
			
			if ( isset($events[$d['year']][$d['mon']][$d['mday']]) )
				$html_classes[] = 'event-presented';
			
			/**/ if ( $t < $first_day_of_month || $t > $last_day_of_month )
				$html_classes[] = 'out-of-month';
			else if ( $n > 5 )
				$html_classes[] = 'weekend';
				
	?>	
			<td class="<?php echo implode(' ', $html_classes); ?>">
			<?php
				if ( isset($events[$d['year']][$d['mon']][$d['mday']]) )
					echo XHtml::link( XHtml::tag('span', array('class' => 'mday'), $d['mday']),
						array('events/'.$d['year'].'/'.sprintf("%02s", $d['mon']).'/'.sprintf("%02s", $d['mday'])) ); 
				else
					echo XHtml::tag('span', array('class' => 'mday'), $d['mday']);
			?>
			</td>
	<?php } ?>
	</tr>
<?php } ?>
</tbody></table></div>

app/protected/views/widgets/thread-posts-wrapper.php
<div id="<?php echo $this->id; ?>" class="<?php echo $this->{'class'}; ?>">
<?php $this->render( 'thread-posts', array('posts' => $posts) ); ?>
</div>

app/protected/views/widgets/thread-posts.php
<?php foreach ($posts as $post): ?>

<div class="forum-post">
	<div class="reference">
		от <span class="author"><?php echo $post->owner_user->name ? $post->owner_user->name : $post->owner_user->login; ?></span>
		<span class="links">
			<?php echo XHtml::link( 'ответить', array('/posts/reply', 'to' => $post->id) ); ?>
		</span>
	</div>
	<div class="timestamp"><?php echo date('d M Y, H:i', $post->timestamp); ?></div>
	<div class="message"><?php echo XHtml::encode($post->message); ?></div>
	<div class="replies"><?php $this->render( 'thread-posts', array('posts' => $post->reply_posts) ); ?></div>
</div>

<?php endforeach ?>